export enum SelectedCourse {
    SOFTWARE_ENGINEERING_1_YEAR = "SOFTWARE_ENGINEERING_1_YEAR",
    WEB_DEVELOPMENT_3_MONTHS = "WEB_DEVELOPMENT_3_MONTHS",
    FULL_STACK_WEB_DEVELOPMENT_6_MONTHS = "FULL_STACK_WEB_DEVELOPMENT_6_MONTHS",
    WORDPRESS_SHOPIFY_WIX_3_MONTHS = "WORDPRESS_SHOPIFY_WIX_3_MONTHS",
}